var timelineMemo = {
    "08/22/2017": {
                    "star2": ["That Which Divides_1016",
                            "Gentle Sunlight_1017",
                            "Closely Watched Heart_1018",
                            "Time Traveler_1019",
                            "That's Not a Doll, Right?_1020",
                            "Reliable Mami-senpai!_1021",
                            "Just a Small Bite!_1022",
                            "Searching for a Ray of Hope_1023",
                            "I'll Never Regret It_1024",
                            "Different Story: Rookies_1025",
                            "Different Story: Mami and Kyoko_1026",
                            "Runway to the World_1027",
                            "By Your Side!_1028",
                            "Science Drunkard_1029",
                            "Busy After School!_1030",
                            "Flowers and Hearts_1031",
                            "These Shoes Are Mine!_1032",
                            "His Place Is Far Away_1033",
                            "Akira's Lovely Room_1034",
                            "Future Three-Star Chef_1035",
                            "Blissful World_1037",
                            "Heart-Melting Pillow_1038",
                            "Max Effort One-Shot Gag_1039",
                            "A World Once Empty_1041",
                            "The Feelings Behind the Bouquet_1042",
                            "This Is the Fragrance of Love_1043",
                            "Putting Sugar in Bitter Black Tea_1044",
                            "Unlimited Happiness to You_1045",
                            "A Brusque Savior_1046",
                            "Hope in Despair_1047",
                            "Towards the End_1048"],
                "star3": [ "She'll Definitely Be Happy_1049",
                            "As a Fashion Model_1050",
                            "The Strongest, Even at Basketball_1051",
                            "It's Not Like I Was Waiting_1052",
                            "PPH! Perfect Callout!_1053",
                            "Surrounded by White Wings_1054",
                            "Tranquil Morning Practice_1055",
                            "First Meeting Combination!_1056",
                            "Let's Eat Together_1057",
                            "Coordinated Combination_1059",
                            "The Hunt Begins_1061",
                            "Keep It Secret!_1062",
                            "The Glasses' Girls Night Out_1063",
                            "Fates Entwined with Madoka_1064",
                            "Splash Party!_1065",
                            "Embrace Your Hopes and Dreams!_1066"],
                "star4": [  "I Won't Stray_1067",
                            "Past and Future_1068",
                            "Onward to the Light!_1069",
                            "Everlasting Light_1070",
                            "Sworn Promise_1071",
                            "Victory Tea_1072"]},
    
    "09/04/2017": {"star2": ["Napping to Your Heart's Content on a Day Off_1103"]},

    "09/19/2017": {"star4": ["Here With You_1107"]},

    "09/29/2017": {"star2": ["My School Life_1112"],
                  "star4": ["Unwavering Belief_1113"]},

    "10/17/2017": {"star2": ["I'm Upside Down!_1119",
                            "Tea for Three_1115",
                            "What's Right Before My Eyes..._1117"],
                    "star4": ["Dependable Negotiator_1121",
                            "I Made Friends!_1122"]}
};

var timelineMeguca = {
    "08/22/2017": {"star2": ["Kanoko Yayoi",
                            "Natsuki Utsuho",
                            "Akira Shinobu",
                            "Sasara Minagi",
                            "Shizuku Hozumi",
                            "Konomi Haruna",
                            "Tsuruno Yui",
                            "Kako Natsume",
                            "Yachiyo Nanami",
                            "Hinano Miyako",
                            "Manaka Kurumi",
                            "Emiri Kisaki",
                            "Felicia Mitsuki",
                            "Sana Futaba"],
                    "star3": [
                            "Ayaka Mariko",
                            "Masara Kagami",
                            "Yuma Chitose",
                            "Rika Ayano",
                            "Aimi Eri",
                            "Nanaka Tokiwa",
                            "Asuka Tatsuki",
                            "Oriko Mikuni",
                            "Meiyui Chun",
                            "Kaede Akino"],
                    "star4": [
                            "Mami Tomoe",
                            "Momoko Togame",
                            "Rena Minami",
                            "Kirika Kure",
                            "Madoka Kaname"]},

    "09/19/2017": {"star4": ["Ren Isuzu"]},

    "09/29/2017": {"star4": ["Kyoko Sakura"]},

    "10/17/2017": {"star4": ["Konoha Shizumi"],
                    "star3": ["Hazuki Yusa"]}
};